
platform :ios, '7.0'
workspace 'QRFounder'  // 这个
link_with 'QRFounder', 'QRFounderPro'
pod 'ZBarSDK', '~> 1.3.1'
pod 'libqrencode', '~> 3.4.2'
pod 'ATMHud@dhoerl', '~> 3.0.0'
pod 'UMengAnalytics'
pod 'UMengFeedback', '~> 2.3.4'
pod 'ReactiveCocoa'
